AESTHETICS = ["1950's Suburbia", "2-Tone", "2000's Autumn", "2010s Internet", "2014-era tumblr",
              "2014 Girly Tumblr", "2020 Alt", "2K1", "2K7", "80s Ballroom", "80s Heart-Throb",
              "Abstract Tech", "Acid Pixie", "Acidwave", "Acubi", "Adventurecore", "Adventure Pulp",
              "Aetherpunk", "Afrofuturism", "Afro-Victorian", "After Hours", "Agropeople", "Ah Beng",
              "Alien", "Alternative", "Amateur Photography", "Americana", "American Pioneers",
              "American Revolution", "American Thanksgiving", "American Tourist Traps", "Amourdoux",
              "Analog Horror", "Ancient Egypt", "Androgynous", "Angelcore", "Anglocore", "Anglo Gothic",
              "Angura", "Animecore", "Anoncore", "Anti-Fashion", "Antique Grunge", "Arcade", "Arcadecore",
              "Art Academia", "Artcore", "Art Deco", "Art Hoe", "Art Nouveau", "Artificial Nature",
              "Arts and Crafts Movement", "Asian Baby Girl", "Athlete", "Atompunk", "Auroracore",
              "Australiana", "Australian Outback", "Autumn", "Autumn Academia", "Avant Apocalypse",
              "Avant-garde", "Babycore", "Babygirl", "Back-to-School", "Baddie", "Baidexweb", "Bakala",
              "Ballet Academia", "Balletcore", "Baltic Violence Tumblr", "Barbiecore", "Bardcore",
              "Baroque", "Bastardcore", "Bauhaus", "BDSM", "Beach Bunny", "Beach Day", "Beach Girl",
              "Beatnik", "Biker", "Bimbocore", "Biopunk", "Bizarro Fiction", "Black Metal", "Bleak Crush",
              "Blokecore", "Blokette", "Bloomcore", "Blue Night", "B-Movie Horror", "Bodikon", "Bohemian",
              "Bombacore", "Bookstore Girl", "Bosozoku", "Boujee", "Breakcore", "Brazilian Pop Bar",
              "Britpop", "Bro", "Bronzepunk", "Bubble Bujo", "Bubble Goth", "Bubblegum Bitch",
              "Bubblegum Dance", "Bubblegum Witch", "Busukawaii", "Cabincore", "Cagole", "Camp", "Campcore",
              "Carnivalcore", "Cartelcore", "Cartooncore", "Casino", "Cassette Futurism", "Cavecore",
              "Celtic", "Changelingcore", "Chaotic Academia", "Chav", "Cheiron Crush", "Cherry Emoji Twitter",
              "Chic Modernist", "Chicano Lowrider", "Cholo", "Choni", "Christcore", "Christian Girl Autumn",
              "Christmas", "Chromecore", "Chunyu", "City Pop", "Classic Academia", "Classicism",
              "Classic Lolita", "Cleancore", "Clockpunk", "Clowncore", "Club", "Club Kids", "Cluttercore",
              "Coastal Grandmother", "Coffee House/Cafe", "Coffinwood", "Comfy/Cozy", "Color Pop",
              "Common White Girl", "Constructivism", "Corporate", "Corporate Grunge", "Corporate Memphis",
              "Corporate Punk", "Cottagecore", "Cottagegore", "Coquette", "Coquette Academia", "Country",
              "Cozy Childhood Hideaway", "C-Pop", "Crackhead", "Craftcore", "Cripplepunk", "Crowcore",
              "Crustpunk", "Cryptid Academia", "Cryptidcore", "Cubism", "Cuddle Party", "Cultcore",
              "Cult Party Kei", "Cutecore", "Cyberdelic", "Cyber Fairy Grunge", "Cyberghetto", "Cybergoth",
              "Cybergrunge", "CyberneticPunk", "Cyberparadism", "Cyberpop", "Cyberprep", "Cyberpunk",
              "Cyberspace Webrooms", "Cyber Stylin’", "Cybervillain", "Danish Pastel", "Dank Meme Voyage",
              "Dark Academia", "Darkcore", "DarkErrorcore", "Darkest Academia", "Dark Fantasy", "Dark Gatsby",
              "Dark Naturalism", "Dark Nautical", "Dark Nymphet", "Dark Paradise", "Dark Y2K", "Daydreampunk",
              "Dazecore", "Deathcore", "Deathrock", "Decopunk", "Decora", "Delicate Sweet", "Denpa Kei",
              "Desertwave", "Desi Romantic Academia", "De Stijl", "Dethereal", "Devilcore", "Dieselpunk",
              "Digital Horror", "Digital Oddity", "Diner", "Dionysism", "Disco", "Dokukawaii",
              "Dollar Store Vernacular", "Dollcore", "Dollette", "Dolly Kei", "Doodlecore", "DORFic",
              "Downtown Girl", "Dracopunk", "Dragoncore", "Drain", "Dreamcore", "Dream Punk", "Dreamy",
              "Driftcore", "Drugcore", "Dual Kawaii", "Dullcore", "Dungeoncore", "Dungeonpunk",
              "Dungeon Synth", "Dutch Golden Age", "Earthcore", "E-Boy", "E-Girl", "Edgy Meme",
              "ElectroPop 08", "Electro Swing", "Elizabethan England", "Emo", "English Major", "Equestrian",
              "Erokawa", "Eshay", "Ethereal", "Europunk", "EXEcore", "Expressionism", "Fairy Academia",
              "Fairycore", "Fairy Grunge", "Fairy Kei", "Fairy Tale", "Fanfare", "Fantasy", "Fantasy Astronomy",
              "FantasY2K", "Farmer's Daughter", "Fashwave", "Fauvism", "Feísmo", "Femboy", "Femcel Weeaboo",
              "Femme Fatale", "Feralcore", "Fieldcore", "Film Noir", "Flapper", "Flat Design",
              "Floral Academia", "Folk Punk", "Foodie", "Forestpunk", "French Girl", "French Girly",
              "Frogcore", "Frutiger Aero", "Frutiger Eco", "Frutiger Metro", "Funky Seasons", "Furry",
              "Future Funk", "Futurism", "Gadgetpunk", "Game Night", "Gamercore", "Gamine", "Gangstæxtemism",
              "Gangstas with Waifus", "Gardencore", "Geek", "Gen X Soft Club", "Gen Z Maximalism",
              "Ghostcore", "Girl-Next-Door", "Glam Girl", "Glamorous Los Angeles", "Glam Rock",
              "Glassmorphism", "Glitchcore", "Global Village Coffeehouse", "Gloomcore", "Glowwave",
              "Goblin Academia", "Goblincore", "Golden Age of Detective Fiction", "Golden Hour",
              "Goofcore", "Gopnik", "Gorecore", "Gorpcore", "Goth", "Gothcore", "Gothic", "Gothic Lolita",
              "Grandmillenial", "Grandparentcore", "Grasscore", "Greaser", "Green Academia", "Grey Academia",
              "Grifes", "Grindhouse", "Gross-Out Horror", "Groundcore", "Grunge", "Gurokawa", "Gyaru",
              "Hair Metal", "Halloween", "Hallyu", "Happycore", "Hatecore", "Hauntology", "Haussmann Paris",
              "Health Goth", "Heatwave", "Heisei Retro", "Heistcore", "Hellenic", "Helvetica Aqua Aero",
              "Hermaphroditus", "Hermitpunk", "Hexatron", "Highlandcore", "High School Dream", "Hikecore",
              "Hime Lolita", "Hi-NRG", "Hip-Hop", "Hipness Purgatory", "Hippie", "Hipster",
              "Historical Americana", "Holosexual", "Home 2K", "Honeycore", "Horror", "Horror Academia",
              "Hot Topic", "Hydrogen", "Hyperpop", "Icepunk", "Imaginarium", "Impressionism", "Indicolite",
              "Indie", "Indiecraft", "Indie Kid", "Indie Sleaze", "Internet Academia", "I-Spy",
              "Italian Mafia", "Italian Renaissance", "Italo Disco", "Itasha", "Jamcore", "Japanese New Left",
              "Jejemon", "Jersey Shore", "Jock", "Joyride", "Juggalo", "Junglecore", "Jungle Grunge",
              "Kaguras", "Karasu Zoku", "Kawaii", "Kawaii Gamer", "Key West Kitten", "Kidcore",
              "Kid Science", "Kimoicore", "Kinderwhore", "Kingcore", "King Gas", "Kiwiana", "Knightcore",
              "Kogal", "Korean Cozy Beige", "Kuromicore", "Labcore", "Laborwave", "Lagenlook", "Larme Kei",
              "La Sape", "Late 2000s Elementary School", "Libertywave", "Lichencore", "Light Academia",
              "Lightcore", "Lightningwave", "Lilac Femme", "Lil Girl", "Liminal Space", "Lit Kid",
              "Lobotomy-Chic", "Lo-Fi", "Lolita", "Long Island", "Lounge", "Lovecore", "Low Poly",
              "Lunarpunk", "Luxury", "Macaute", "Mad Scientist", "Magepunk", "Magewave", "Magical Girls",
              "Maidcore", "Mallgoth", "Mall Ninja", "Mallsoft", "Manguebeat", "Mansfieldcore", "Maximalism",
              "McBling", "Meatcore", "Medicalcore", "Medieval", "Medieval Fantasy", "Memphis", "Mermaid",
              "Messy French Girl", "Metal", "Metalcore", "Metalheart", "Metrosexual", "Miami Metro",
              "Midwest Emo", "Midwest Gothic", "Military", "Milk", "Mind Murder", "Miniaturecore", "Minimalism",
              "Minivan Rock", "Miscellaneous Academia", "Mizuiro", "MLG", "Mod", "Modernism", "Monumentality",
              "Mori Kei", "Morute", "Motomami", "Mosscore", "Mote Kei", "Movida Madrileña", "MS Paint",
              "MTV Green Sky", "Mulchcore", "Mushroomcore", "Musical Academia", "Mythpunk", "Nanchatte Seifuku",
              "Nanopunk", "NATOwave", "Naturecore", "Nautical", "Nautical Fantasy", "Nazi Chic", "Neko",
              "Neoclassicism", "Neo-Romanism", "Neo-Tokyo", "Neo-Vikings", "Nerd", "Nerdcore", "Neumorphism",
              "New Age", "New England Gothic", "New Figuration", "New Money", "New Romantic", "New Wave",
              "Night Luxe", "Nintencore", "Normcore", "Northerness", "Nostalgiacore", "Nuclear", "Nu-Goth",
              "Nu-Metal", "Nu-Punk", "Nymphet", "Ocean Academia", "Ocean Grunge", "Oceanpunk", "Offlinecore",
              "Olderbrothercore", "Old Hollywood", "Old Memecore", "Old Money", "Old Web", "Onii Kei",
              "Oshare Kei", "Otaku", "Otherkin", "Pachuco", "Pale Grunge", "Paleocore", "Palewave",
              "Paramilitary", "Party Animal", "Party Kei", "Pastel Academia", "Pastel Gore", "Pastel Goth",
              "Pastel Punk", "PC Music", "Peach", "Peaky Blinders", "Pearly", "Peoplehood", "Petcore",
              "Phony Bureaucracy", "Photorealism", "Pig in Jacuzzicore", "Pink Parisian", "Pink Pilates Princess",
              "Pink Princess", "Pin-up", "Pirate", "Pixel Cutie", "Pixel Medieval Fantasy", "Pixelscape",
              "Pixiecore", "Plaguecore", "Plant Mom", "Playboy", "Poetcore", "Poolcore", "Pop Art", "Pop Kei",
              "Post-Apocalyptic", "Post-Impressionism", "Post-Punk", "Post-rock", "Powwow Step", "Prairiecore",
              "Prehistoricore", "Preppy", "Prehistoricore", "Pre-Raphaelite", "Pretty Preppy", "Pride flags",
              "Princecore", "Princesscore", "Printcore", "Progressive Academia", "Psychedelica", "Psychonaut",
              "Punk", "Purism", "Quality Tumblr", "Queencore", "Queer Academia", "Queercore", "Queer Villainy",
              "R&B", "Racaille", "Ragecore", "Rainbowcore", "Rainy Day", "Randumb", "Rangercore", "Ratcore",
              "Ravencore", "Raver", "Raxet", "Raygun Gothic", "Real Life Super Hero", "Realism", "Rebel Academia",
              "Red Academia", "Reefwave", "Regency", "Regional Gothic", "Renewable Corporate Futurism",
              "Retro Fairycore", "Retro-Futurism", "Rivethead", "Roaring 20s", "Robotcore", "Robotics Kids",
              "Rock", "Rockabilly", "Rocketpunk", "Rockstar GF", "Rococo", "Roguecore", "Rollerwave",
              "Romantic Academia", "Romantic Goth", "Romanticism", "Romantic Italian", "Rotcore", "Royalcore",
              "Rusticcore", "Sacricore", "Sad people", "Salon Kei", "Salvagepunk", "Sandalpunk", "Sanriocore",
              "Scene", "Schizowave", "Science Academia", "Scoutcore", "Scrapbook", "Scrapper", "Seapunk",
              "Sega Uranus", "Selkiecore", "Shabby Chic", "Shamate", "Shanzhai", "Sharpies", "Shibuya Punk",
              "Shiny Suit 97", "Shironuri", "Shoegaze", "Sigilkore", "Sigma Male", "Silicon Dreams",
              "Silkpunk", "Sizz", "Skater", "Skeuomorphism", "Skinheads", "Slimepunk", "Sloanie",
              "Sleepycore", "Slutcore", "Smilecore", "Snow Bunny", "Snowdrop", "Social Science Academia",
              "Soft Apocalypse", "Soft Colonial Wanderlust", "Soft Countriana", "Soft Grunge", "Softie",
              "Soft Indie", "Soft Macabre", "Soft Morningcore", "Soggy", "Solarpunk", "Southern Belle",
              "Southern Gothic", "Soviet", "Soviet Bloc School", "Sovietwave", "Spacecore", "Sparklecore",
              "Spiritcore", "Spriggancore", "Spring", "Spy Fiction", "Starrflesh", "Steampunk", "Steelpunk",
              "Stellar Scholar", "Stilyagi", "Stimwave", "Stonepunk", "Stoner", "Stripcore", "Studyblr",
              "Studyplace", "Suburban Gothic", "Sukeban", "Summer", "Superflat Pop", "Suprematism",
              "Surf Crush", "Surrealism", "Surreal Memer", "Sweet Lolita", "Swenkas", "Swordpunk",
              "Synthwave", "Tacticool", "Taisho Roman", "Takenokozoku", "Tanbi Kei", "Tango",
              "Technical Scene", "Technocore", "Technoneko2000", "Technozen", "Techwear", "Teddies",
              "Teenage Dream", "Teenagers in the Woods", "Teenqueen", "Telstracore", "TenderCore",
              "Terrorwave", "Teslapunk", "That Girl", "Theatre Academia", "Theatre Kids", "Thrasher",
              "Thriftcore", "Tiki", "Tinkercore", "Tinycore", "Tomboy", "Toxic Core", "Toycore",
              "Trad Goth", "Trailer Park Princess", "Trashcore", "Trashy Raver", "Traumacore",
              "Trenchcore", "Trendercore", "Trillwave", "Tropical", "Tumblewave", "Tupinipunk",
              "Twee", "Tweencore", "Ukiyo-e", "Ultraviolet Crush", "Unicorncore", "Uptown Girl",
              "Urban Fantasy", "Urbancore", "UrBling", "Utopian Scholastic", "Vacation Dadcore",
              "Vampire", "Vaporwave", "VARIOUSXYZ", "Vectorbloom", "Vectorheart", "Vh1 Sepia Sky",
              "Vibrant Academia", "Victorian", "Victorian Goth", "Victorian Urban Poverty", "Viking",
              "Villagecore", "Villaincore", "Vintage Americana", "Vintage British Sportsman",
              "Vintage Hero", "Vintage Parisian", "Virgo's Tears", "Visual Kei", "Voidcore", "Voidpunk",
              "Vorticism", "VSCO", "VSCO Preppy", "Vulture Culture", "Wabi-Sabi", "Waif", "Waldorf",
              "Wanderlust", "Warmcore", "Weathercore", "Web Creep", "Weeaboo", "Weirdcore", "Welwitschia Goth",
              "Werewolf", "Western", "Wetcore", "Whimsigothic", "Wild Child", "Winter", "Winter Academia",
              "Winter Fairy Coquette", "Witchcore", "Witch House", "Witchy Academia", "Wizardcore",
              "Wonderland", "Woodland Goth", "Wormcore", "Writer Academia", "Wuxia", "XO", "Y2K", "Yakuza",
              "Yami Kawaii", "Yandere", "Yankeecore", "Yanki", "Yellow Academia", "Youthquake",
              "Yume Kawaii", "Zombiecore"]